language: generic
sudo: required
services:
    - docker


before_install:
    - docker build - lypukachi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lypukachi/docker-react npm run test

